### ISSUE TITLE
Unable to change settings to 100 songs; error message says otherwise

### ISSUE THREAD

**Issue by jasondamico** [P-bibs/MixCapsule#1]
Under the "Options" menu, I tried to set the number of songs in my playlist to 100. An error message appeared on the screen (see below screenshot), but it said that I had to input a number 1-100. Some quick trials showed that this message seems to appear for all numbers [51, 100] - I also know that [the limit of the number of the user's top t tracks that can be retrieved by the API is 50](https://developer.spotify.com/documentation/web-api/reference/personalization/get-users-top-artists-and-tracks/).

![mixcapsule_screenshot](https://user-images.githubusercontent.com/51730872/94514105-5e3f8f00-01ee-11eb-9cc9-e2021c90e236.JPG)

**Comment by P-bibs** [comment]
Fixed in #2
